//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForwardPhishingToAbuseAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultConfigStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultConfigStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForwardPhishingToAbuseAddin.Properties.DefaultConfigStrings", typeof(DefaultConfigStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a user-submitted report of a phishing email delivered by $PluginName$. Please review the attached phishing email(s).
        /// </summary>
        internal static string Mail_MailBody {
            get {
                return ResourceManager.GetString("Mail_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security@mycompany.com.
        /// </summary>
        internal static string Mail_MailTo {
            get {
                return ResourceManager.GetString("Mail_MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email message selected.
        /// </summary>
        internal static string Messages_NoEmailSelectedTitle {
            get {
                return ResourceManager.GetString("Messages_NoEmailSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected message(s) will be forwarded to $SecurityTeamEmail$ and removed from your inbox.
        ///    
        ///Would you like to continue?.
        /// </summary>
        internal static string Messages_ReportingConfirmationMessage {
            get {
                return ResourceManager.GetString("Messages_ReportingConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Phishing to your security team.
        /// </summary>
        internal static string Messages_ReportingConfirmationTitle {
            get {
                return ResourceManager.GetString("Messages_ReportingConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an email message to continue..
        /// </summary>
        internal static string NoEmailSelectedMessage {
            get {
                return ResourceManager.GetString("NoEmailSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  according to the process defined in $RunbookUrl$ ..
        /// </summary>
        internal static string ProcessAddendumIfRunbookUrlConfigured {
            get {
                return ResourceManager.GetString("ProcessAddendumIfRunbookUrlConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Phishing.
        /// </summary>
        internal static string ReportingButtonLabel {
            get {
                return ResourceManager.GetString("ReportingButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Phishing Email.
        /// </summary>
        internal static string ReportingButtonScreenTip {
            get {
                return ResourceManager.GetString("ReportingButtonScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button to report suspicious emails to the Information Security team..
        /// </summary>
        internal static string ReportingButtonSuperTip {
            get {
                return ResourceManager.GetString("ReportingButtonSuperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [$PluginName$] Phishing Email Report.
        /// </summary>
        internal static string ReportingEmailSubject {
            get {
                return ResourceManager.GetString("ReportingEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Phishing Email.
        /// </summary>
        internal static string RibbonGroupName {
            get {
                return ResourceManager.GetString("RibbonGroupName", resourceCulture);
            }
        }
    }
}
